import React,{useState}from"react";
import{Activity,AlertTriangle,ChevronDown,HeartPulse,Moon,ShieldCheck,Stethoscope,Sun}from"lucide-react";
const CONDITIONS=[
{name:"Common cold",summary:"May include a runny nose, sneezing, sore throat, and mild cough.",goal:"Relieve symptoms while the immune system clears the viral infection.",treatments:[{name:"Rest and fluids",helps:"Supports recovery and helps prevent dehydration."},{name:"Saline nasal spray",helps:"Moistens nasal passages and may ease congestion."},{name:"Pharmacist-guided symptom relief",helps:"May reduce discomfort when appropriate for the individual."}],escalation:"Get assessed if symptoms are severe, worsening, persistent, or accompanied by breathing difficulty, dehydration, confusion, or chest pain."},
{name:"Seasonal influenza",summary:"May include fever, body aches, tiredness, headache, and cough.",goal:"Maintain hydration, reduce discomfort, and identify people needing early clinical care.",treatments:[{name:"Rest, fluids, and monitoring",helps:"Supports recovery and helps identify worsening symptoms."},{name:"Clinician-approved fever or pain relief",helps:"May reduce fever and body aches when safe for the individual."},{name:"Prescription antiviral assessment",helps:"A clinician may consider antiviral treatment for eligible or higher-risk patients."}],escalation:"Get prompt clinical advice for severe illness, worsening symptoms, pregnancy, immune suppression, young children, older adults, or serious long-term conditions."},
{name:"Allergic rhinitis",summary:"May include sneezing, itchy or runny nose, and watery eyes.",goal:"Reduce exposure to triggers and control allergic inflammation.",treatments:[{name:"Trigger reduction",helps:"Limiting exposure to known allergens may reduce the reaction."},{name:"Saline nasal rinse",helps:"May wash allergens and mucus from nasal passages when used safely."},{name:"Clinician or pharmacist-guided allergy treatment",helps:"An appropriate antihistamine or nasal treatment may ease symptoms."}],escalation:"Get urgent help for breathing difficulty or facial or throat swelling. Arrange assessment if symptoms persist or remain uncontrolled."}
];
const danger=["chest pain","can't breathe","cannot breathe","fainting","severe bleeding","weakness on one side"];
export default function App(){const[dark,setDark]=useState(false),[text,setText]=useState(""),[result,setResult]=useState(null),[open,setOpen]=useState(null);function analyze(){const t=text.toLowerCase();setResult(danger.some(x=>t.includes(x))?"urgent":"standard");setTimeout(()=>document.querySelector("#results")?.scrollIntoView({behavior:"smooth"}),50)}return <div className={dark?"app dark":"app"}>
<header><div className="brand"><span className="logo"><HeartPulse/></span><div><b>MediGuide AI</b><small>Educational health assistant</small></div></div><div className="head-actions"><span className="privacy"><ShieldCheck size={16}/> Privacy-first demo</span><button className="icon" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun/>:<Moon/>}</button></div></header>
<main><section className="hero"><div><span className="eyebrow"><Activity size={15}/> Safer next-step guidance</span><h1>Understand symptoms.<br/><em>Choose safer next steps.</em></h1><p>Review educational possibilities, urgent warning signs, and clinician-reviewed treatment information explaining how each option may help.</p><div className="ticks"><span>✓ No diagnosis claims</span><span>✓ Emergency checks</span><span>✓ Human review required</span></div></div><div className="safety"><Stethoscope size={34}/><h2>Important treatment safety</h2><p>This prototype does not prescribe medicines or doses. Treatment suitability depends on age, pregnancy, allergies, existing conditions, and other medicines.</p></div></section>
<section className="workspace"><div className="form card"><span className="step">STEP 1 OF 2</span><h2>Tell us what you feel</h2><p className="muted">Do not enter your name, ID number, address, or other private details.</p><label>Describe your symptoms</label><textarea value={text} maxLength={500} onChange={e=>setText(e.target.value)} placeholder="Example: I have had a dry cough, headache, and tiredness for two days..."/><div className="count">{text.length}/500</div><button className="primary" disabled={text.trim().length<8} onClick={analyze}>Review symptoms</button></div>
<aside className="card warning"><AlertTriangle/><h3>Get urgent help now for</h3><ul><li>Severe trouble breathing</li><li>New or severe chest pain</li><li>Fainting or confusion</li><li>Uncontrolled bleeding</li><li>Sudden one-sided weakness</li></ul><strong>Use local emergency services. Do not wait for an app response.</strong></aside></section>
{result&&<section id="results" className="card results">{result==="urgent"?<div className="urgent"><AlertTriangle size={36}/><div><span className="step">URGENT RESULT</span><h2>Urgent warning signs detected</h2><p>Stop using this demo and seek emergency medical care now.</p></div></div>:<><span className="step">EDUCATIONAL RESULT</span><h2>Possibilities to discuss with a clinician</h2><p className="muted">These are examples, not a diagnosis. Treatment information must be reviewed for the individual by a qualified professional.</p><div className="conditions">{CONDITIONS.map((c,i)=><article className="condition" key={c.name}><button className="condition-head" onClick={()=>setOpen(open===i?null:i)}><div><span className="possible">POSSIBLE</span><h3>{c.name}</h3><p>{c.summary}</p></div><ChevronDown className={open===i?"rotate":""}/></button>{open===i&&<div className="details"><h4>Treatment goal</h4><p>{c.goal}</p><h4>Treatment options and how they may help</h4>{c.treatments.map(t=><div className="treatment" key={t.name}><b>{t.name}</b><span>{t.helps}</span></div>)}<div className="escalate"><b>When to get medical care</b><span>{c.escalation}</span></div></div>}</article>)}</div></>}</section>}
</main><footer>Educational prototype only • No diagnosis • No prescription • Human clinical oversight required</footer></div>}
